database:
  connection_string: "mongodb://localhost:27017"
  database_name: "communities"

paths:
  data_directory: "../../api/history/"

logging:
  level: "INFO"

import:
  granularity: "daily" # possible: daily, hourly